/// Mazos de Edison Format con su imagen (circular, en assets/decks/):
/// - Competitivo / Rogue / Casual: https://edisonformat.net/decks
/// - Más mazos: https://formatlibrary.com/deck-gallery/edison
/// La imagen de cada mazo es el arte de la carta más representativa; los mazos
/// que combinan dos arquetipos llevan media imagen de cada uno. Se cargan en la
/// BD al abrir la app; los que no están aquí se pueden añadir a mano.
library;

enum DeckCategory { competitive, rogue, casual, more, custom }

extension DeckCategoryLabel on DeckCategory {
  String get label => switch (this) {
        DeckCategory.competitive => 'Competitivo',
        DeckCategory.rogue => 'Rogue',
        DeckCategory.casual => 'Casual',
        DeckCategory.more => 'Más mazos',
        DeckCategory.custom => 'Añadidos',
      };
}

class DeckCatalogEntry {
  const DeckCatalogEntry(this.name, this.category, this.slug);

  final String name;
  final DeckCategory category;
  final String slug;

  String get asset => 'assets/decks/$slug.webp';
}

const kDeckCatalog = <DeckCatalogEntry>[
  DeckCatalogEntry('Blackwing', DeckCategory.competitive, 'blackwing'),
  DeckCatalogEntry('Vayu Turbo', DeckCategory.competitive, 'vayu_turbo'),
  DeckCatalogEntry('Hybrid Blackwing', DeckCategory.competitive, 'hybrid_blackwing'),
  DeckCatalogEntry('Hero Frog', DeckCategory.competitive, 'hero_frog'),
  DeckCatalogEntry('Junk Frog', DeckCategory.competitive, 'junk_frog'),
  DeckCatalogEntry('Diva Zombie', DeckCategory.competitive, 'diva_zombie'),
  DeckCatalogEntry('Diva Hero', DeckCategory.competitive, 'diva_hero'),
  DeckCatalogEntry('Diva Hero Beat', DeckCategory.competitive, 'diva_hero_beat'),
  DeckCatalogEntry('Dragon Turbo', DeckCategory.competitive, 'dragon_turbo'),
  DeckCatalogEntry('Lightsworn', DeckCategory.competitive, 'lightsworn'),
  DeckCatalogEntry('Machina', DeckCategory.competitive, 'machina'),
  DeckCatalogEntry('Amaryllis', DeckCategory.rogue, 'amaryllis'),
  DeckCatalogEntry('Cat', DeckCategory.rogue, 'cat'),
  DeckCatalogEntry('Dragon Aggro', DeckCategory.rogue, 'dragon_aggro'),
  DeckCatalogEntry('Fairy', DeckCategory.rogue, 'fairy'),
  DeckCatalogEntry('Fish OTK', DeckCategory.rogue, 'fish_otk'),
  DeckCatalogEntry('Flamvell', DeckCategory.rogue, 'flamvell'),
  DeckCatalogEntry('Gladiator Beast', DeckCategory.rogue, 'gladiator_beast'),
  DeckCatalogEntry('Hero Beat', DeckCategory.rogue, 'hero_beat'),
  DeckCatalogEntry('Norleras', DeckCategory.rogue, 'norleras'),
  DeckCatalogEntry('Quickdraw Plant', DeckCategory.rogue, 'quickdraw_plant'),
  DeckCatalogEntry('Ancient Gear', DeckCategory.rogue, 'ancient_gear'),
  DeckCatalogEntry('Diva FLIP', DeckCategory.rogue, 'diva_flip'),
  DeckCatalogEntry('Gemini', DeckCategory.rogue, 'gemini'),
  DeckCatalogEntry('Gravekeeper', DeckCategory.rogue, 'gravekeeper'),
  DeckCatalogEntry('Hopeless Dragon', DeckCategory.rogue, 'hopeless_dragon'),
  DeckCatalogEntry('Kuraz', DeckCategory.rogue, 'kuraz'),
  DeckCatalogEntry('Machina Gadget', DeckCategory.rogue, 'machina_gadget'),
  DeckCatalogEntry('Machina Roid', DeckCategory.rogue, 'machina_roid'),
  DeckCatalogEntry('Quickdraw Volcanic', DeckCategory.rogue, 'quickdraw_volcanic'),
  DeckCatalogEntry('TeleDAD', DeckCategory.rogue, 'teledad'),
  DeckCatalogEntry('Alien', DeckCategory.casual, 'alien'),
  DeckCatalogEntry('Anti-Meta', DeckCategory.casual, 'anti_meta'),
  DeckCatalogEntry('Assault Mode', DeckCategory.casual, 'assault_mode'),
  DeckCatalogEntry('Batteryman', DeckCategory.casual, 'batteryman'),
  DeckCatalogEntry('Black Salvo', DeckCategory.casual, 'black_salvo'),
  DeckCatalogEntry('Bushi', DeckCategory.casual, 'bushi'),
  DeckCatalogEntry('Cloudian', DeckCategory.casual, 'cloudian'),
  DeckCatalogEntry('Codarus', DeckCategory.casual, 'codarus'),
  DeckCatalogEntry('Crystal Beast', DeckCategory.casual, 'crystal_beast'),
  DeckCatalogEntry('Dark Gaia', DeckCategory.casual, 'dark_gaia'),
  DeckCatalogEntry('Earthbound Immortal', DeckCategory.casual, 'earthbound_immortal'),
  DeckCatalogEntry('Fortune Lady', DeckCategory.casual, 'fortune_lady'),
  DeckCatalogEntry('Insect', DeckCategory.casual, 'insect'),
  DeckCatalogEntry('Koa\'ki Meiru', DeckCategory.casual, 'koaki_meiru'),
  DeckCatalogEntry('Neo-Spacian', DeckCategory.casual, 'neo_spacian'),
  DeckCatalogEntry('Monster Mash', DeckCategory.casual, 'monster_mash'),
  DeckCatalogEntry('Morphtronic', DeckCategory.casual, 'morphtronic'),
  DeckCatalogEntry('Ojama', DeckCategory.casual, 'ojama'),
  DeckCatalogEntry('Psychic', DeckCategory.casual, 'psychic'),
  DeckCatalogEntry('Relinquished', DeckCategory.casual, 'relinquished'),
  DeckCatalogEntry('Six Samurai', DeckCategory.casual, 'six_samurai'),
  DeckCatalogEntry('Spaceship', DeckCategory.casual, 'spaceship'),
  DeckCatalogEntry('Uria', DeckCategory.casual, 'uria'),
  DeckCatalogEntry('X-Saber', DeckCategory.casual, 'x_saber'),
  DeckCatalogEntry('Frog Monarch', DeckCategory.more, 'frog_monarch'),
  DeckCatalogEntry('Machina Control', DeckCategory.more, 'machina_control'),
  DeckCatalogEntry('Frog OTK', DeckCategory.more, 'frog_otk'),
  DeckCatalogEntry('Lightsworn Fairy', DeckCategory.more, 'lightsworn_fairy'),
  DeckCatalogEntry('Gigavise', DeckCategory.more, 'gigavise'),
  DeckCatalogEntry('Dragon Beat', DeckCategory.more, 'dragon_beat'),
  DeckCatalogEntry('Diva Frog', DeckCategory.more, 'diva_frog'),
  DeckCatalogEntry('Zombie TeleDAD', DeckCategory.more, 'zombie_teledad'),
  DeckCatalogEntry('Diva Hero Zombie', DeckCategory.more, 'diva_hero_zombie'),
  DeckCatalogEntry('Jinzo Machina', DeckCategory.more, 'jinzo_machina'),
  DeckCatalogEntry('Cat Control', DeckCategory.more, 'cat_control'),
  DeckCatalogEntry('Ancient Gear Machina', DeckCategory.more, 'ancient_gear_machina'),
  DeckCatalogEntry('Chain Burn', DeckCategory.more, 'chain_burn'),
  DeckCatalogEntry('Cat Plant', DeckCategory.more, 'cat_plant'),
  DeckCatalogEntry('Phantom Turbo', DeckCategory.more, 'phantom_turbo'),
  DeckCatalogEntry('Plant Frog', DeckCategory.more, 'plant_frog'),
  DeckCatalogEntry('Macro Monarch', DeckCategory.more, 'macro_monarch'),
  DeckCatalogEntry('Machina Hero', DeckCategory.more, 'machina_hero'),
  DeckCatalogEntry('Evil Hero', DeckCategory.more, 'evil_hero'),
  DeckCatalogEntry('Flamvell Zombie', DeckCategory.more, 'flamvell_zombie'),
  DeckCatalogEntry('Twilight', DeckCategory.more, 'twilight'),
  DeckCatalogEntry('Volcanic Garden', DeckCategory.more, 'volcanic_garden'),
  DeckCatalogEntry('Dark Rock Stun', DeckCategory.more, 'dark_rock_stun'),
  DeckCatalogEntry('Macro Stun', DeckCategory.more, 'macro_stun'),
  DeckCatalogEntry('Ancient Gear Plant', DeckCategory.more, 'ancient_gear_plant'),
  DeckCatalogEntry('Gadget', DeckCategory.more, 'gadget'),
  DeckCatalogEntry('Zombie Plant', DeckCategory.more, 'zombie_plant'),
  DeckCatalogEntry('Machina Frog', DeckCategory.more, 'machina_frog'),
  DeckCatalogEntry('Demise OTK', DeckCategory.more, 'demise_otk'),
  DeckCatalogEntry('Zombie Turbo', DeckCategory.more, 'zombie_turbo'),
  DeckCatalogEntry('Anti-Meta Stun', DeckCategory.more, 'anti_meta_stun'),
  DeckCatalogEntry('Diva Hero Frog', DeckCategory.more, 'diva_hero_frog'),
  DeckCatalogEntry('Turbo Frog', DeckCategory.more, 'turbo_frog'),
  DeckCatalogEntry('Virus Drain Beat', DeckCategory.more, 'virus_drain_beat'),
  DeckCatalogEntry('Mausoleum Frog', DeckCategory.more, 'mausoleum_frog'),
  DeckCatalogEntry('Zombie', DeckCategory.more, 'zombie'),
  DeckCatalogEntry('Flamvell Lightsworn', DeckCategory.more, 'flamvell_lightsworn'),
  DeckCatalogEntry('Dark Plant', DeckCategory.more, 'dark_plant'),
  DeckCatalogEntry('Assault Turbo', DeckCategory.more, 'assault_turbo'),
  DeckCatalogEntry('Diva Cat', DeckCategory.more, 'diva_cat'),
  DeckCatalogEntry('Twilight Vayu Turbo', DeckCategory.more, 'twilight_vayu_turbo'),
  DeckCatalogEntry('Fertilizer Control', DeckCategory.more, 'fertilizer_control'),
  DeckCatalogEntry('Frog Quickdraw Plant', DeckCategory.more, 'frog_quickdraw_plant'),
  DeckCatalogEntry('Ancient Gear Machina Plant', DeckCategory.more, 'ancient_gear_machina_plant'),
  DeckCatalogEntry('Soul Control', DeckCategory.more, 'soul_control'),
  DeckCatalogEntry('Plant Control', DeckCategory.more, 'plant_control'),
  DeckCatalogEntry('Tethys Turbo', DeckCategory.more, 'tethys_turbo'),
  DeckCatalogEntry('Lightsworn Monarch', DeckCategory.more, 'lightsworn_monarch'),
  DeckCatalogEntry('Quickdraw Machina', DeckCategory.more, 'quickdraw_machina'),
  DeckCatalogEntry('Neo-Spacian Quickdraw Plant', DeckCategory.more, 'neo_spacian_quickdraw_plant'),
  DeckCatalogEntry('Chaos Fairy', DeckCategory.more, 'chaos_fairy'),
  DeckCatalogEntry('Gigavise Gemini Beat', DeckCategory.more, 'gigavise_gemini_beat'),
  DeckCatalogEntry('Frog Control', DeckCategory.more, 'frog_control'),
  DeckCatalogEntry('Cat Garden', DeckCategory.more, 'cat_garden'),
  DeckCatalogEntry('Gemini Beat', DeckCategory.more, 'gemini_beat'),
  DeckCatalogEntry('Machina Salvo DAD', DeckCategory.more, 'machina_salvo_dad'),
  DeckCatalogEntry('Virus Dragon', DeckCategory.more, 'virus_dragon'),
  DeckCatalogEntry('Quickdraw Hero', DeckCategory.more, 'quickdraw_hero'),
  DeckCatalogEntry('Salvo DAD', DeckCategory.more, 'salvo_dad'),
  DeckCatalogEntry('Hero Quickdraw Plant', DeckCategory.more, 'hero_quickdraw_plant'),
  DeckCatalogEntry('Nurse Burn', DeckCategory.more, 'nurse_burn'),
  DeckCatalogEntry('60-Card Dark', DeckCategory.more, '60_card_dark'),
  DeckCatalogEntry('Fusion Gate Hero', DeckCategory.more, 'fusion_gate_hero'),
  DeckCatalogEntry('Neo-Spacian Diva Hero', DeckCategory.more, 'neo_spacian_diva_hero'),
  DeckCatalogEntry('Volcanic Quickdraw Plant', DeckCategory.more, 'volcanic_quickdraw_plant'),
  DeckCatalogEntry('Machina Cat', DeckCategory.more, 'machina_cat'),
  DeckCatalogEntry('Dragon Plant', DeckCategory.more, 'dragon_plant'),
  DeckCatalogEntry('Gear Machina Hero Beat', DeckCategory.more, 'gear_machina_hero_beat'),
  DeckCatalogEntry('Exodia FTK', DeckCategory.more, 'exodia_ftk'),
  DeckCatalogEntry('Vaskii Turbo', DeckCategory.more, 'vaskii_turbo'),
  DeckCatalogEntry('Flamvell Cat', DeckCategory.more, 'flamvell_cat'),
  DeckCatalogEntry('Machina Volcanic Quickdraw', DeckCategory.more, 'machina_volcanic_quickdraw'),
  DeckCatalogEntry('Diva Macro Stun', DeckCategory.more, 'diva_macro_stun'),
  DeckCatalogEntry('Dark Gaia Turbo', DeckCategory.more, 'dark_gaia_turbo'),
  DeckCatalogEntry('Gravekeeper Burn', DeckCategory.more, 'gravekeeper_burn'),
  DeckCatalogEntry('Quickdraw Frog', DeckCategory.more, 'quickdraw_frog'),
  DeckCatalogEntry('Vayu Control', DeckCategory.more, 'vayu_control'),
  DeckCatalogEntry('Virus Frog', DeckCategory.more, 'virus_frog'),
  DeckCatalogEntry('Zombie Vayu Turbo', DeckCategory.more, 'zombie_vayu_turbo'),
  DeckCatalogEntry('Diva Hero Vayu Turbo', DeckCategory.more, 'diva_hero_vayu_turbo'),
  DeckCatalogEntry('Rock Stun', DeckCategory.more, 'rock_stun'),
  DeckCatalogEntry('Black Garden', DeckCategory.more, 'black_garden'),
  DeckCatalogEntry('PACMAN', DeckCategory.more, 'pacman'),
  DeckCatalogEntry('Counter Fairy', DeckCategory.more, 'counter_fairy'),
  DeckCatalogEntry('Bazoo Return', DeckCategory.more, 'bazoo_return'),
  DeckCatalogEntry('Mist Valley Frog', DeckCategory.more, 'mist_valley_frog'),
  DeckCatalogEntry('UO Junk Frog', DeckCategory.more, 'uo_junk_frog'),
  DeckCatalogEntry('Phantom Twilight', DeckCategory.more, 'phantom_twilight'),
  DeckCatalogEntry('Zombie World', DeckCategory.more, 'zombie_world'),
  DeckCatalogEntry('Immortal Beat', DeckCategory.more, 'immortal_beat'),
  DeckCatalogEntry('Chaos Hero', DeckCategory.more, 'chaos_hero'),
  DeckCatalogEntry('Diva Plant', DeckCategory.more, 'diva_plant'),
  DeckCatalogEntry('Machina Quickdraw Plant', DeckCategory.more, 'machina_quickdraw_plant'),
  DeckCatalogEntry('Calculator', DeckCategory.more, 'calculator'),
  DeckCatalogEntry('Chaos Zombie', DeckCategory.more, 'chaos_zombie'),
  DeckCatalogEntry('Exodia', DeckCategory.more, 'exodia'),
  // Añadido a mano (imagen: Jinzo).
  DeckCatalogEntry('Jinzo OTK', DeckCategory.more, 'jinzo_otk'),
  // Mazos del Torneo #1 · T4 2026 (imágenes enviadas por el organizador).
  DeckCatalogEntry('Dream Frogs', DeckCategory.more, 'dream_frogs'),
  DeckCatalogEntry('Hero Stun', DeckCategory.more, 'hero_stun'),
  DeckCatalogEntry('Dark Hero Frog', DeckCategory.more, 'dark_hero_frog'),
  DeckCatalogEntry('Simochi Burn', DeckCategory.more, 'simochi_burn'),
  DeckCatalogEntry('Valhalla Fairies', DeckCategory.more, 'valhalla_fairies'),
  DeckCatalogEntry('Instant Zombie', DeckCategory.more, 'instant_zombie'),
  DeckCatalogEntry('GB Turbo', DeckCategory.more, 'gb_turbo'),
  DeckCatalogEntry('X-Insects', DeckCategory.more, 'x_insects'),
];

/// Nombres viejos que son el mismo mazo que otro del catálogo. Al abrir la app
/// se fusionan solos (partidas, inscripciones y estadísticas pasan al nuevo).
const Map<String, String> kDeckAliases = {
  'hybrid': 'Hybrid Blackwing',
  'dark jinzo otk': 'Jinzo OTK',
};

/// Entrada del catálogo por nombre normalizado (minúsculas, espacios simples).
final Map<String, DeckCatalogEntry> kDeckCatalogByName = {
  for (final e in kDeckCatalog) e.name.toLowerCase(): e,
};
